export {
  PRICE_HEADERS,
  PRICE_HEADERS_DIARIO,
  PRICE_KEY_FESTIVO,
  PRICE_KEY_LEGACY_FESTIVO,
  PRICE_KEY_SEXTO_DIA,
  PRICE_KEY_SEXTO_DIA_HALF,
  FACTOR_SEXTO_DIA,
  FESTIVO_PRICE_FIELD_ALIASES,
  SEXTO_DIA_PRICE_FIELD_ALIASES,
  SEXTO_DIA_HALF_PRICE_FIELD_ALIASES,
  migrateConditionsPrices,
  migratePriceRow,
  migratePricesMap,
} from './shared/priceKeys';

export const PRICE_ROLES: string[] = [
  'Gaffer',
  'Best boy',
  'Eléctrico',
  'Auxiliar',
  'Meritorio',
  'Rigging Gaffer',
  'Rigging Best Boy',
  'Rigging Eléctrico',
  'Técnico de mesa',
  'Finger boy',
  'Grupista eléctrico',
  'Chofer eléctrico',
  'Eléctrico de potencia',
  'Técnico de prácticos',
];
